citusdata/pg_cron

src/job_metadata.c

Fix a crash when passing an invalid schedule to cron.schedule, i.e. cron.schedule('foobar', $$SELECT 1$$)

Avoid freeing a NULL pointer

---

src/pg_cron.c

`pg_usleep` might not respond immediately in case of a postmaster crash. We separately need to address `poll`.

Replace pg_usleep with WaitLatch, check for postmaster death

---

Makefile

A user reported on slack that they can't compile pg-cron using gcc-7. This change in Makefile suppresses compilation error.

Disable implicit fallthrough error in gcc-7 compiler

---

Makefile
src/job_metadata.c
src/pg_cron.c

* Suppress warnings about maybe uninitialized variables in entry.c
* Correctly handle jobId as 64bit int
Spotted while building Debian packages for apt.postgresql.org.

Porting fixes

---

CHANGELOG.md
Makefile
expected/pg_cron-test.out
include/cron_job.h
include/job_metadata.h
pg_cron--1.0--1.1.sql
pg_cron.control
pg_cron.sql
sql/pg_cron-test.sql
src/job_metadata.c
src/task_states.c

o To be able to switch on and off cron.job(s) we introduced a new
column 'active' on cron.job table. This allows us to simply enable
or disable a job without modifiing the schedule.
o In addition a regression test was added to test the upgrade path.
Simply run 'make installcheck' to execute the test.
o Increased pg_cron version to 1.1.

Add a 'active' column on con.job table to simply enable and disable jobs

---

README.md

Not sure if this is fine, but since I've written a simple blog post about `pg_cron` a few days ago, I thought it could be useful adding the link to the use cases in the `README.md` file.
In the case you don't want to add it, that's fine and just close this PR.

Added blog post to README "use cases".

---

include/pg_cron.h
src/job_metadata.c
src/pg_cron.c
src/task_states.c

The macro was needed with early PostgreSQL versions in the 11.x
branch that introduced AllocSetContextCreateExtended().
Later this was simplified (see commit 13cd7209 in Postgres)
and starting with 12.x we must call AllocSetContextCreate()
again.

Call AllocSetContextCreate() directly rather than through a macro.

---

README.md

Versions before 10 can't directly install version 1.2 which only exists
as 1.0 -> 1.1 -> 1.2 upgrade path.
Spotted by the Debian regression tests.

Fix installation instructions for PostgreSQL 9.x

---

Makefile
include/cron_job.h
include/job_metadata.h
include/task_states.h
pg_cron--1.2--1.3.sql
pg_cron.control
src/job_metadata.c
src/pg_cron.c

This PR is mainly made of 4 commits:
1. background worker support
2. audit table support
3. job and task wording
4. renamed bgworker scheduler to launcher
This commit is adding support for using background workers instead of libpq sessions to execute the jobs.
This behavior is guarded behind a GUC and disabled by default so that it does not impact backward compatibility.
The background workers use a similar technique to the `pg_background` extension to run commands, and things like cron.host, nodename, and nodeport have no effect in this mode.
This commit is adding support for an audit table.
It works for either libpq or background-worker mode.
content looks like:
```
postgres=# select * from cron.job_run_details;
jobid | runid | job_pid | database | username |                  command …
```

adding support for using background workers instead of libpq + adding support for an audit table

---

expected/pg_cron-test.out
include/cron_job.h
include/job_metadata.h
pg_cron--1.2--1.3.sql
sql/pg_cron-test.sql
src/job_metadata.c

Adds a jobname column and new schedule/unschedule definitions that take a name instead of a job ID.
Fixes #24

Allow jobs to be scheduled by name

---

src/entry.c

There is a small typo in src/entry.c.
Should read `implemented` rather than `implmented`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, implmented -> implemented

---

expected/pg_cron-test.out
pg_cron--1.3--1.4.sql
pg_cron.control
sql/pg_cron-test.sql
src/job_metadata.c

Add options to the schedule() function: can specify a database, username,...  
Create a new function: alter_job() to give the ability to alter an existing job (change database, username, schedule, command...)  
* **Only superuser** can create a job with another username or alter an existing job with another username.
* When database is specified (in schedule() or alter_job()), then a check is done to ensure that the database exists and also that the username that will be part of the job can connect to it.
```
postgres=> create user cront with password 'bdt';
CREATE ROLE
postgres=> create extension pg_cron;
CREATE EXTENSION
postgres=> GRANT USAGE ON SCHEMA cron TO cront;
GRANT
postgres=> create database dbyes;
CREATE DATABASE
postgres=> create database dbno;
CREATE DATABASE
postgres=> …
```

add alter_job() and update schedule() with more options

---

src/job_metadata.c

Make sure to always reset the memory context after committing in metadata functions to avoid doing future allocations in the top memory context.
Fixes #128

Always reset memory context in job_metadata functions

---

README.md

We are proud to have pg_cron available on Aiven too, so adding the link to the list.

Add Aiven to the list of cloud providers with pg_cron support

---

src/pg_cron.c

Hi. The code logic palloc a CronTask structure array, but assigns it to a pointer of two-dimension array. So the space is subsequently used as a pointer array whose type is `CronTask *`, instead of a structure array. There is no error thrown yet because the size of a `CronTask *` pointer is much less than a `CronTask` structure, so only the front part of the whole allocated space is used and an out-of-bound will never happen. But it is actually no need to allocate so much memory that won't be used.

Palloc for pointer array instead of struct array

---

expected/pg_cron-test.out
include/job_metadata.h
sql/pg_cron-test.sql
src/job_metadata.c
src/pg_cron.c

Per request, add an option to disallow running jobs as superuser altogether to support set ups in which there is a highly privileged user that is allowed to write to cron.job and therefore allowed to schedule jobs as other users, without implicitly granting superuser privileges.

Add cron.enable_superuser_jobs option to disallow superuser jobs

---

.gitignore
Makefile
pg_cron.conf

This PR adds extra options to the pg_regress, enabling the
support to create a functional postgres instance to run the tests
without a server running.
Also updated `.gitignore` file with the files created by the pg_regress.
Signed-off-by: Sebastian Webber <sebastian@swebber.me>
Co-authored-by: Guilherme Elias <elias@ongres.com>

add regress options to run installcheck

---

src/pg_cron.c

Since ProcessCompletedNotifies() is removed in 15, and there is no need
to call it for bgworker, so I think we can remove it.
Discussion: https://www.postgresql.org/message-id/flat/153243441449.1404.2274116228506175596%40wrigleys.postgresql.org
Commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=2e4eae87d02fef51c42c2028b65d85b9e051f9eb

Support PostgreSQL 15

---

src/job_metadata.c

Spotted on arm, mips, and powerpc platforms on Debian.

AlterJob: Fix error printf format on 32-bit architectures

---

Makefile
pg_cron--1.4--1.4-1.sql
pg_cron.control

Doing pg_dump on the whole database as a non-superuser is a little cumbersome when pg_cron is installed.
```bash
$ pg_dump -U dumper 
pg_dump: error: query failed: ERROR:  permission denied for sequence jobid_seq           
pg_dump: error: query was: SELECT last_value, is_called FROM cron.jobid_seq   
```
By granting select on the sequences to public it becomes slightly easier.
```bash
$ pg_dump -U dumper
...
pg_dump: error: query failed: ERROR:  query would be affected by row-level security policy for table "job"
pg_dump: error: query was: COPY cron.job (jobid, schedule, command, nodename, nodeport, database, username, active, jobname) TO stdout;
$ pg_dump -U dumper --enable-row-security
...
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA public;  
COPY cron.job (jobid, schedule, …
```

Grant select to sequences to simplify pg_dump as non-superuser

---

README.md

The support for the pg_cron extension has been added to Google Cloud SQL ([release notes](https://cloud.google.com/sql/docs/postgres/release-notes#November_19_2021)).
Also update the [link](https://cloud.google.com/sql/postgresql) for Google Cloud SQL for PostgreSQL.

Update Google Cloud SQL support for pg_cron

---

src/pg_cron.c

pg_cron can cause crash of PostgreSQL instance if task is running during "unschedule" call. Crash happens during next cycle of launcher after task completion. 
Here is stack trace:
```
(gdb) bt
#0  0x00007f5a553c49ef in ShouldRunTask (schedule=0x10, currentTime=<optimized out>, doWild=<optimized out>, doNonWild=<optimized out>) at src/pg_cron.c:945
#1  0x00007f5a553c6b1c in StartPendingRuns (task=0x2da8398, task=0x2da8398, currentTime=697539660000563, lastMinute=<optimized out>, clockProgress=CLOCK_PROGRESSED) at src/pg_cron.c:792
#2  StartAllPendingRuns (currentTime=697539660000563, taskList=0x2d63820) at src/pg_cron.c:749
#3  PgCronLauncherMain (arg=<optimized out>) at src/pg_cron.c:650
#4  0x00000000006ccfcf in StartBackgroundWorker () at bgworker.c:911
#5  0x00000000006d8f63 in …
```

fix crash after unschedule during running task

---

src/pg_cron.c

- Rename pg_analyze_and_rewrite to pg_analyze_and_rewrite_fixedparams
- Call CHECK_FOR_INTERRUPTS after resetting Latch in order to properly
handle SIGUSR1. It wasn't a problem until recent fixes of DROP
{DATABASE,TABLESPACE} on Windows: postgres/postgres@4eb2176

Compatibility with PostgreSQL 15

---

src/pg_cron.c

postgres master branch(a.k.a release 16) add a feature *Default to hidden visibility for extension libraries where possible*[1], this will cause problem when loading the pg_cron shared library.
```
ERROR:  could not find function "PgCronLauncherMain"
```
add PGDLLEXPORT can solve the problem.
[1] https://github.com/postgres/postgres/commit/089480c077056fc20fa8d8f5a3032a9dcf5ed812
Signed-off-by: Junwang Zhao <zhjwpku@gmail.com>

add PGDLLEXPORT to adapt pg 16

---

src/job_metadata.c

in NextRunId, we are generating runId but not jobId, fix the typo.
Signed-off-by: Junwang Zhao <zhjwpku@gmail.com>

[typo] %s/jobId/runId/g in NextRunId

---

expected/pg_cron-test.out
sql/pg_cron-test.sql

This fixes the testsuite to run with PG 12 and earlier.
ERROR:  return type mismatch in function declared to return text DETAIL:  Actual return type is name.
Close #195.

tests: Fix compatibility with PG<=12

---

src/entry.c

When the return value of char type function under arm environment is EOF, -1 will be converted to 255, because the char type under arm is defaulted to unsigned char

Fix: the parameters of the scheduled task cannot be verified in the arm environment

---

README.md

Output for 4 of the 5 examples does not include the row count. This removes the row count from the 5th example for consistency.

docs: standardize example output

---

README.md
src/pg_cron.c

Dear hackers, I think GMT time will cause us more troubles in actual use. So I added a guc parameter to help users choose their own time zone. Here's one of my suggestions that I think will work well. Looking forward to your reply.

Support GUC parameter: cron.timezone

---

src/pg_cron.c

We can reuse SIGTERM handler of regular backends instead of duplicating it for cron workers. It also keeps up to date with PG code.

Reuse backend SIGTERM handler for cron workers

---

src/task_states.c

This pull request fixes #214 
Previously:
```
$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -Wshadow=compatible-local -fPIC -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/usr/local/pgsql/include -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE   -c -o src/pg_cron.o src/pg_cron.c -MMD -MP -MF .deps/pg_cron.Po
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security …
```

Fix variable shadowing

---

README.md

As per example description, this job should run weekly, not daily.

Fix weekly example to really run on Sunday

---

include/cron_job.h
include/job_metadata.h
pg_cron--1.4-1--1.5.sql
pg_cron.control
src/job_metadata.c

Job name being a name field is causing some issues.
This will require an ALTER EXTENSION / is likely to cause some issues when the schema is stale.
Fixes #196

Make job name a text field

---

src/job_metadata.c

Showing internal implementation details in pg_stat_activity mostly causes confusion, plus it's not used consistently, removing.

Remove pg_stat_activity reporting from job metadata queries

---

include/task_states.h
src/pg_cron.c

We should pass `nowait` to `shm_mq_receive` to continue while the background worker is running.
Closes #200 
Closes #229

Fix issue #200 preventing concurrent background workers

---

README.md
expected/pg_cron-test.out
include/cron.h
include/task_states.h
sql/pg_cron-test.sql
src/entry.c
src/job_metadata.c
src/pg_cron.c
src/task_states.c

By popular demand, fixes #6.
Extends the schedule syntax to allow defining jobs based on an interval in seconds that starts when pg_cron learns about the job, shortly after scheduling or server boot. The interval is measured from the start of the last run. If a run takes longer than the interval, the next run starts immediately after, which resets the interval timer.
We opted to define a job purely based on an interval because adding another part to the cron schedule would make the schedule hard to read, incompatible with typical crontab tools, and the level of control over when in the week the "per x second" job happens seems unnecessary. Moreover, we usually cannot guarantee when a job happens down to the second on busy servers, so we'll make no attempt to do so.
Syntax is as follows, …

Add possibility to schedule jobs by interval in seconds

---

pg_cron--1.2--1.3.sql

same as #192, this fix avoid operator override during extension upgrade.
Signed-off-by: Junwang Zhao <zhjwpku@gmail.com>

avoid attacker to override operator

---

src/job_metadata.c
src/pg_cron.c

pgcron does not build agaist postgres upstream because pg 16 has the following two changes:
1. c727f511bd7bf3c58063737bcf7a8f331346f253 refactor aclcheck functions, use one common `object_aclcheck` to replace all dozens of mostly-duplicate `pg_foo_aclcheck()` functions.
2. 0a20ff54f5e66158930d5328f89f087d4e9ab400 introduced utils/guc_hooks.h and removed commands/variable.h
This patch address these issues and make pg_cron compile agaist postgres version 16.
Signed-off-by: Junwang Zhao <zhjwpku@gmail.com>

fix pg 16 compile error

---

src/pg_cron.c

time_t depends on the current architecture:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-uninitialized -Wno-implicit-fallthrough -Iinclude -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE …
```

Use correct time type on 32-bit systems

---

src/job_metadata.c

After job name was converted to a text field in 6fc9ca9 there is a problem in updating the extension from the versions where the field is of type name. Namely: when postgres is started - the extenision is still not updated, thus, the column type is not yet altered, pg_cron launcher gets a Segmentation Fault during the attempt to convert a heap tuple from cron.job table to a CronJob struct.
Steps to reproduce:
1. Compile and install pg_cron pre-1.5 (e.g. 1.4-1)
2. Schedule a job with a name
3. Compile and install pg_cron 1.5
4. Restart cluster
```
,LOG,00000,"background worker ""pg_cron launcher"" (PID 796233) was terminated by signal 11: Segmentation fault",,,,,,,,,"","postmaster",,0
```
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, …
```

Fix jobname field handling

---

expected/pg_cron-test.out
sql/pg_cron-test.sql

The 1.4 version of the SQL scripts are no longer compatible with the C code since cron_unschedule_named expects "text" as input now.
Instead of hardcoding '1.4', simply upgrade to the most recent version. Also drop the test for extversion after the upgrade since this value is prone to be missed on future releases.
Problem was visible on big-endian architectures.
https://github.com/citusdata/pg_cron/issues/267
Close #267.

Test latest version instead of hardcoding 1.4

---

src/job_metadata.c

_entry *schedule_ local variable is declared twice in ParseSchedule.
src/job_metadata.c: In function ‘ParseSchedule’:
src/job_metadata.c:1526:10: error: declaration of ‘schedule’ shadows a previous local [-Werror=shadow=compatible-local]
1526 |   entry *schedule = calloc(sizeof(entry), sizeof(char));
|          ^~~~~~~~
src/job_metadata.c:1514:9: note: shadowed declaration is here
1514 |  entry *schedule = parse_cron_entry(scheduleText);
|         ^~~~~~~~
cc1: all warnings being treated as errors
make: *** [../../src/Makefile.global:949: src/job_metadata.o] Error 1

fix warning- "declaration shadows a  previous local"

---

src/entry.c

I found a bug of vixie cron, which bit_nset and bit_nclear are used to set and clean bits of range [start, stop], for `dow` and `hour`, they use 8 bits and 24bits, the following statement will write the next byte since the pass the length instead of the stop position, which will corrupt the memory.
bit_nset(e->hour, 0, (LAST_HOUR-FIRST_HOUR+1));
bit_nset(e->dow, 0, (LAST_DOW-FIRST_DOW+1));
bit_nclear(bits, 0, (high-low+1));
Paul vixie(the author of vixie cron) fix this with some code refactory, this patch just backport it back to pg_cron.
The original PRs:
1. https://github.com/vixie/cron/pull/16
2. https://github.com/vixie/cron/pull/18

fix memory corruption bug of cron module

---

src/entry.c
src/misc.c

clang-15 with PG16 finally chokes on them.
```
20:30:42 /usr/bin/clang-15 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-uninitialized -Wno-implicit-fallthrough -Iinclude -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/16/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o src/entry.bc src/entry.c
20:30:42 src/entry.c:243:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
20:30:42 get_list(bits, low, high, names, ch, file) …
```

Convert K&R function definitions

---

src/pg_cron.c

I think the proc_exit(0) was done at an early stage to have a way of disabling the background worker in case it went haywire. By now pg_cron is quite battle-tested and can be mostly disabled using `cron.launch_active_jobs`, and users often accidentally kill the scheduler.
Fixes #188

Restart pg_cron scheduler when terminating the background worker

---

pg_cron--1.2--1.3.sql

The migration script for pg_cron 1.2 to 1.3 was using nextval() without qualifying it with pg_catalog. This is a problem if the user has installed pg_cron in a schema other than pg_catalog. This commit fixes the problem by qualifying the function call.

Qualify function call in migration script

---

CHANGELOG.md
src/pg_cron.c

pg_localtime always returns a pointer to the tm struct in https://github.com/postgres/postgres/blob/master/src/timezone/localtime.c#L104 , causing tomorrow time to override current time, which meant pg_cron always scheduled day-of-months jobs from tomorrow.
Introduced by #273
Fixes #290
Fixes #288

Fix pointer reuse bug causing off-by-1 day of month

---

src/job_metadata.c

When calling `cron.schedule_in_database` on an existing job, both the `schedule` and the `command` are updated to the new values, but not the `database`.
This PR adds the extra update statement so the `database` can also be updated.

Update the database when scheduling an existing job

---

expected/pg_cron-test.out
sql/pg_cron-test.sql
src/job_metadata.c

The PostgreSQL-recommended way to handle this would have been to introduce a new C symbol for the new signature.  It's too late for that, so use get_fn_expr_argtype() to discover the caller's expectations. Fixes https://github.com/citusdata/pg_cron/issues/267.

Make cron_unschedule_named() accept v1.4 SQL signature.

---

src/job_metadata.c

Hi, Postgres 17 Beta 1 is out and I noticed pg_cron has a small compatibility issue with it. This commit should fix that. It assumes pg_cron is not interested in supporting PG versions before 9.5 based on what the README implies about supported versions being PG 10 and higher.
---
(The following is the commit message)
MemoryContextResetAndDeleteChildren will be retired in the upcoming PG 17 [0]. It has been equivalent to MemoryContextReset since PG 9.5 [1]. The reference to MemoryContextResetAndDeleteChildren is thus replaced by MemoryContextReset for compatibility purposes.
[0] https://github.com/postgres/postgres/commit/6a72c42fd5af7ada49584694f543eb0
[1] https://github.com/postgres/postgres/commit/eaa5808e8ec4e82ce1a87103a6b6f68

Replace MemoryContextResetAndDeleteChildren macro with MemoryContextReset for PG 17 compatibility

---

Makefile

Hi,
When I try to use pg_cron on Illumos, there are some errors, such as following:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wsign-compare -ggdb -O0 -ftree-vectorize -pipe -fexceptions -Wl,-rpath,/home/japin/postgres/build/pg/lib -fPIC -fvisibility=hidden -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/home/japin/postgres/build/pg/include -I. -I./ -I/home/japin/postgres/build/pg/include/server -I/home/japin/postgres/build/pg/include/internal …
```

Fix compiler error on Illumos

---

expected/pg_cron-test.out
include/job_metadata.h
sql/pg_cron-test.sql
src/job_metadata.c
src/pg_cron.c

The callback was registered only for bgworker and as a result client backends were failing to unschedule jobs if the extension was droped and recreated in the same session:
```
CREATE EXTENSION pg_cron;
SELECT cron.schedule('0 10 * * *', 'VACUUM');
SELECT cron.unschedule(1);
DROP EXTENSION pg_cron;
CREATE EXTENSION pg_cron;
SELECT cron.schedule('0 10 * * *', 'VACUUM');
SELECT cron.unschedule(1);
ERROR:  could not open relation with OID 16388
```
Update, just found out that this issue is already discovered (#344) and there is a fix (#345) that takes different approach.

Fix bug with invalidation of CachedCronJobRelationId

---

expected/pg_cron-test.out
sql/pg_cron-test.sql
src/job_metadata.c

The #299 PR took care of bacward compatibility of the function, but there is still one problem left. If extension isn't updated type of the jobname field in the cron.job table is still NAME, and as a result scan was failing to find rows and unschedule a named job.
This fix is relying on the fact that SQL API of the unschedule() function is updated consistently with the cron.job table definition.

Select procedure based on argument type of cron_unschedule_named

---

README.md

YugabyteDB now fully supports the pg_cron extension.

Add YugabyteDB to list of supported services

---

README.md

Hi there, 
Instaclustr now supports pg_cron natively on our platform. Would be great if the readme could reflect that?
Chris

Updated readme to show that Instaclustr now supports pg_cron

---

src/entry.c

Hi! Im getting an compiler errors, which are surely false-positive, but lets get compiler quiet?
```
cc1: all warnings being treated as errors
make: *** [/usr/local/cbdb/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:1031: src/pg_cron.o] Error 1 make: *** Waiting for unfinished jobs....
In function ‘get_range’,
inlined from ‘get_list’ at src/entry.c:308:8,
inlined from ‘parse_cron_entry’ at src/entry.c:195:8:
src/entry.c:413:26: error: ‘num3’ may be used uninitialized [-Werror=maybe-uninitialized]
412 |         if (num1 < low || num1 > high || num2 < low || num2 > high ||
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
413 |                 num3 < 0 || num3 > high)
|                 ~~~~~~~~~^~~~~~~~~~~~~~
src/entry.c: In function ‘parse_cron_entry’: …
```

Fix maybe-uninitialized compile warn.

---

src/pg_cron.c

There is a mismatch condition from vixie cron, which is introduced by me.
Please see this commit [0] and give a careful review, this might related to
issue #329.
[0] https://github.com/vixie/cron/commit/6934bc3b8315015449f1ab4e17657cfc04e00df0#diff-0dd69331a6e6206ccce46bb571314ca252a70ddbbcc4f0807422fc9f0e5f9a14L321

fix mismatch condition from vixie cron

---

src/pg_cron.c

Currently, the pg_cron scheduler repeats every message that it receives from a background worker as LOG, and every message that it receives from a libpq connection to stderr. Neither is very practical in production environments with procedures that might throw a lot of notices.
This PR proposes to suppress notices altogether and to avoid repeating warnings, which the original process already logged.
Fixes #350

Stop logging notices and repeating log messages

---

src/pg_cron.c

I was trying to build pg_cron against the current postgres master and noticed this blip.
commit message follows
`
525392d from postgres upstream adds a new argument in PortalDefineQuery, CachedPlanSource. The CachedPlan in this call is NULL so naturally CachedPlanSource is passed NULL here.
`

Update PortalDefineQuery call for postgres 18 compatibility
